In [1]:
# Basic Matrix Algebra
# Author: Zhang Su (Teaching Assistant)
# Using python3, numpy
# 15 June 2020

# Learning Outcome

By the end of this material, you should be able to:

+ Carry out all the basic matrix operations using Python Numpy,
+ Translate long matrix equations to Python Numpy for calculation.

Note: 
1. If you occasionally double clicked a textual cell, the display would change to markdown source code. To reverse, simply click anywhere of that markdown cell,  and then click **Run** in the top manu.
2. Sometimes the notebook may not be responding. That is caused by the failure of jupyter kernel. To repair, try clicking **Kernel** in the top manu, then clicking **Reconnect**. 
3. Section Takeaways summarizes useful tips, e.g., holes of Python to avoid, if any.
4. Section Practice reflect the learning outcomes. You are expected to solve them based on your understanding on the lecture notes alone with the coding skills learned from this demo.

# Table of contents <a name="Table_of_Content"></a>
+ 7.2.2. [Inverse](#Inverse)
+ 7.2.2. [Transpose](#Transpose)
+ 7.2.2. [Transpose and Inverse](#TI)
+ 7.2.2. [Trace](#Trace)
+ 7.2.2. [Determinant](#Determinant)
+ 7.2.3. [Orthogonal Matrix Examples](#OME)
+ [Practice](#Practice)

The demo today will show how to do basic matrix operation in Python. Let's import the libraries.

In [2]:
import numpy as np
from numpy import linalg as la

### Inverse<a name="Inverse"></a>
[Return to Table of Content](#Table_of_Content)

Given an invertible matrix
$A=\begin{pmatrix}
1&2&4\\
0&0&5\\
0&3&6
\end{pmatrix}$, we would like to examine $AA^{-1}=A^{-1}A=I$, where $I$ is a $3\times 3$ identity matrix. You will see that $AA^{-1}$ and $A^{-1}A$ are "almost" the same. (You may use `.round(4)` to restrict the decimal.)

In [3]:
A = np.array([[1,2, 4],
            [0,0,5],
            [0,3,6]], dtype=float)

A_inv = la.inv(A)

print("AA^-1 = \n", A.dot(A_inv))
print("A^-1A = \n", A_inv.dot(A))

# A_pinv = la.pinv(A) # You may also try the pseudo inverse

AA^-1 = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
A^-1A = 
 [[ 1.0000000e+00  0.0000000e+00  8.8817842e-16]
 [ 0.0000000e+00  1.0000000e+00 -4.4408921e-16]
 [ 0.0000000e+00  0.0000000e+00  1.0000000e+00]]


### Transpose <a name="Transpose"></a>
[Return to Table of Content](#Table_of_Content)

The transpose operation is shown below.

In [4]:
A = np.array([[25,20,3,2],
            [5,10,15,25],
            [6,16,7,27]], dtype=float)

Transpose_of_A = A.T

print("A = \n", A)
print("The transpose of A = \n", Transpose_of_A)

A = 
 [[25. 20.  3.  2.]
 [ 5. 10. 15. 25.]
 [ 6. 16.  7. 27.]]
The transpose of A = 
 [[25.  5.  6.]
 [20. 10. 16.]
 [ 3. 15.  7.]
 [ 2. 25. 27.]]


### Transpose and Inverse <a name="TI"></a>
[Return to Table of Content](#Table_of_Content)

Here we would like to examine $(A^{-1})^T=(A^T)^{-1}$.

In [5]:
A = np.array([[0,1,0],
            [0,0,3],
            [5,0,0]], dtype=float)

A_inv_T = la.inv(A).T
A_T_inv = la.inv(A.T)

print("Are they eqyal?", np.allclose(A_inv_T, A_T_inv))

Are they eqyal? True


### Trace<a name="Trace"></a>
[Return to Table of Content](#Table_of_Content)

Given a matrix $A=\begin{pmatrix}
15 & 6 & 7\\
2 & -4 & 2\\
3 & 2 & 6
\end{pmatrix}$, the trace is the sum of all the diagonal entries, i.e., $tr(A)=15+(-4)+6=17$.


The trace operation is shown below.

In [6]:
A = np.array([[15,6, 7],
            [2,-4,2],
            [3,2,6]], dtype=float)

trace_of_A = A.trace()

print("A = \n", A)
print("Its trace = \n", trace_of_A)

A = 
 [[15.  6.  7.]
 [ 2. -4.  2.]
 [ 3.  2.  6.]]
Its trace = 
 17.0


### Determinant<a name="Determinant"></a>
[Return to Table of Content](#Table_of_Content)

The determinant of a matrix is calculated as below.

In [7]:
A = np.array([[15,6, 7],
            [2,-4,2],
            [3,2,6]], dtype=float)

determinant_of_A = la.det(A)

print("A = \n", A)
print("Its determinant = \n", determinant_of_A)

A = 
 [[15.  6.  7.]
 [ 2. -4.  2.]
 [ 3.  2.  6.]]
Its determinant = 
 -343.99999999999994


### Orthogonal Matrix Examples<a name="OME"></a>
[Return to Table of Content](#Table_of_Content)

Let us verify $U^{-1}=U^T$ given an orthogonal matrix $U$.

In [8]:
A = np.array([[15,6, 7],
            [2,-4,2],
            [3,2,6]], dtype=float)

U, _ = la.qr(A)

print("Are they eqyal?", np.allclose(la.inv(U), U.T))

Are they eqyal? True


#### Example 1. 

Solve for $X$ given $AX(D+BX)^{-1}=C$. For this equation to agree, all matrices are square and invertible.

The derivation is as follows:

$$
\begin{align}
AX(D+BX)^{-1}&=C \tag{1} \\
AX&=C(D+BX) \\
AX&=CD+CBX \\
(A-CB)X &= CD \\
X &= (A-CB)^{-1}CD \tag{2}
\end{align}
$$

In Python, we need just write Eq. 1 and Eq. 2 as follows.

In [9]:
m, n = 3, 3

A = np.random.rand(m, n) - 0.5
B = np.random.rand(m, n) - 0.5
D = np.random.rand(m, n) - 0.5
X = np.random.rand(m, n) - 0.5

# Eq. 1
C = A.dot(X).dot(la.inv(D + B.dot(X)))

# Eq. 2
X_estimated = la.inv(A - C.dot(B)).dot(C.dot(D))

print("The original X = \n", X)
print("The estimated X = \n", X_estimated)
print("Their difference = \n", (X - X_estimated).round(5))

The original X = 
 [[-0.01629988 -0.36807481  0.32919293]
 [-0.38487237 -0.1196886  -0.13768521]
 [ 0.15182328 -0.09078862 -0.44874622]]
The estimated X = 
 [[-0.01629988 -0.36807481  0.32919293]
 [-0.38487237 -0.1196886  -0.13768521]
 [ 0.15182328 -0.09078862 -0.44874622]]
Their difference = 
 [[ 0.  0. -0.]
 [-0. -0.  0.]
 [-0. -0.  0.]]


#### Example 2.

Solve for $X$ given $(AX)^T((D+BD)^-1)^T=I$. For this equation to agree, all matrices are square and invertible.

The derivation is as follows:

$$
\begin{align}
(AX)^T\left((D+BX)^{-1}\right)^T&=I \tag{3} \\
(AX)^T&=I\cdot\left(\left((D+BX)^{-1}\right)^T\right)^{-1} \\
X^TA^T&=I\cdot\left(\left((D+BX)^T\right)^{-1}\right)^{-1} \\
X^TA^T&=I\cdot(D+BX)^T \\
X^TA^T&=I\cdot D^T+X^TB^T \\
X^TA^T-X^TB^T&=I\cdot D^T \\
X^T(A^T-B^T)&=I\cdot D^T \\
X^T &= I\cdot D^T\cdot(A^T-B^T)^{-1} \\
X &= \left(I\cdot D^T\cdot(A^T-B^T)^{-1}\right)^T \tag{4}
\end{align}
$$

In [1]:
# This one is for your practice :)
# m, n = 3, 3

# A = np.random.rand(m, n) - 0.5
# B = np.random.rand(m, n) - 0.5
# D = np.random.rand(m, n) - 0.5

# # Eq. 4
# X = (D.T.dot(la.inv(A.T-B.T))).T

# # Eq. 3
# check_I = A.dot(X).T.dot(la.inv(D+B.dot(X)).T)


# print("The output = \n", check_I.round(4))

### Practice<a name="Practice"></a>
[Return to Table of Content](#Table_of_Content)

**This part can get you ready for the lab!**

1. In this question, we seek to implement Eq. (4) first, and then substitute $X$ into the left hand side of Eq. (3) to see whether the right hand side is an identity matrix. (All the procedures are already exampled in Example 1.)
    + Generate three $4\times 4$ random matrix using `np.random.rand(m, n)-0.5`.
    + Obtain $X$ by Eq. (4).
    + Calculate the right hand side of Eq. (3).
    + verify that the right hand side of Eq. (3) is close to a $4\times 4$ identity matrix.