# Lab 4
## 4. Tasks
### Question 4A

In [1]:
import numpy as np
from numpy import linalg as la
from random import randint
from statistics import mean

In [2]:
# Q4A. Given matrix A (mxn) and a vector b (nx1), find x/x_hat such that Ax = b
# a. Solve for x using pseudo inverse, save x as x1a vector
m, n = 3, 2
A = np.random.rand(m,n)
b = np.random.rand(m,1)
print("A =\n", A)
print("b =\n", b)

A_inv = la.pinv(A)
x1a = A_inv@b
print("\nUsing pseudo inverse,\nx1a = \n", x1a)

A =
 [[0.67457202 0.95879171]
 [0.43277381 0.50043456]
 [0.29641171 0.20186787]]
b =
 [[0.87197314]
 [0.58394218]
 [0.53890822]]

Using pseudo inverse,
x1a = 
 [[ 2.19021473]
 [-0.64844377]]


In [3]:
# b. Solve for x using normal equation, save x as x1b vector
# ATAx = ATb
ATA = A.T@A
x1b = la.inv(ATA)@A.T@b
print("Using normal equation, \nx1b = \n", x1b)

Using normal equation, 
x1b = 
 [[ 2.19021473]
 [-0.64844377]]


In [4]:
# c. Are the solutions of pseudo inverse and normal equation same? Why?
if la.norm(x1a - x1b) <= 1e-6:
    print("The solutions are the same.")
else:
    print("The solutions are different.")

The solutions are the same.


In [5]:
# d. Find hat_b using pseudo inverse vs normal equation solution
# Using pseudo inverse
hat_b1a = A@x1a
print("Using pseudo inverse,\nhat_b1a =\n", hat_b1a)

# Using normal equation
hat_b1b = A@x1b
print("\nUsing normal equation,\nhat_b1b =\n", hat_b1b)

# Check if hat_b1a & hat_b1b are the same
if la.norm(hat_b1a - hat_b1b) <= 1e-6:
    print("\nThe results are the same.")
else:
    print("\nThe results are different.")

Using pseudo inverse,
hat_b1a =
 [[0.85573506]
 [0.6233639 ]
 [0.51830533]]

Using normal equation,
hat_b1b =
 [[0.85573506]
 [0.6233639 ]
 [0.51830533]]

The results are the same.


In [6]:
# e. What is the norm of error to approximate b using the two approaches?
# Using pseudo inverse
error_1a = b - hat_b1a
norm_error_1a = la.norm(error_1a)
print("Using pseudo inverse,\nnorm of error to approximate b = ", norm_error_1a)

#Using normal equation
error_1b = b - hat_b1b
norm_error_1b = la.norm(error_1b)
print("\nUsing normal equation,\nnorm of error to approximate b = ", norm_error_1b, "\n")

# Is x1a and x1b different? Why? Which solution is better if different?
if abs(norm_error_1a - norm_error_1b) < 1e-6:
    print("Both approach produces the same error to approximate b.")
else:
    print("The two approaches produce different error to approximate b.")
    if norm_error_1a < norm_error_1b:
        print("Pseudo inverse produces a better solution.")
    else:
        print("Normal equation produces a better solution.")

Using pseudo inverse,
norm of error to approximate b =  0.04735215828881798

Using normal equation,
norm of error to approximate b =  0.04735215828881794 

Both approach produces the same error to approximate b.


In [7]:
# f. Is b in the column space of A? Use at least 2 different ways to show this?
# Method 1: Check if rank of A == rank of [A b]
print("Method 1: Check if rank of A == rank of [A b]")
rank_A = la.matrix_rank(A)
A_b = np.hstack((A,b))
rank_A_b = la.matrix_rank(A_b)
print("rank of A =", rank_A, "\nrank of [A b] =", rank_A_b)
if rank_A == rank_A_b:
    print("b is in column space of A, since rank of A == rank of [A b].")
else:
    print("b is not in column space of A, since rank of A != rank of [A b].")
    
# Method 2: Check if Ax - b == 0
print("\nMethod 2: Check if Ax - b == 0")
if norm_error_1a <= 1e-6:
    print("b is in column space of A")
else:
    print("b is not in column space of A.")

Method 1: Check if rank of A == rank of [A b]
rank of A = 2 
rank of [A b] = 3
b is not in column space of A, since rank of A != rank of [A b].

Method 2: Check if Ax - b == 0
b is not in column space of A.


In [8]:
# g. Is the error vector (produced by normal equation) orthogonal to column space of A?

is_orthogonal = 1
for i in range(n):
    a_i = A[:,i]
    dot_prod_i = np.dot(a_i,error_1b)
    print("a_" + str(i) + ".error_1b =", dot_prod_i)
    if dot_prod_i >= 1e-6:
        is_orthogonal = 0
if is_orthogonal:
    print('''\nThe error vector is orthogonal to column space of A, since 
the dot product of error vector and columns of A equals to zero.''')
else:
    print("The error vector is not orthogonal to column space of A.")

a_0.error_1b = [-2.54136989e-16]
a_1.error_1b = [-5.70724024e-16]

The error vector is orthogonal to column space of A, since 
the dot product of error vector and columns of A equals to zero.


In [9]:
# h. Can we use the normal equation to solve for x in this example?
# Justify your answer? When can we not use the normal equation to solve Least Squares?
rank_ATA = la.matrix_rank(ATA)
if n == rank_ATA:
    print(f'''Yes, because ATA is rank {rank_ATA} for {n} variables.
This implies that ATA is non-singular and its inverse exists.''')
else:
    print(f'''No, because ATA is rank {rank_ATA} for {n} variables. 
This shows that ATA is singular and non-invertible.''')

Yes, because ATA is rank 2 for 2 variables.
This implies that ATA is non-singular and its inverse exists.


In [10]:
# i. Construct Q with orthogonal basis spanning the column space of A using
# QR (reduced form) decomposition
Q, R = np.linalg.qr(A)
print("Q =\n", Q)
print("\nR =\n", R)

Q =
 [[-0.78941844  0.50913982]
 [-0.50645389 -0.22452424]
 [-0.34687604 -0.83088237]]

R =
 [[-0.85451769 -1.08035801]
 [ 0.          0.20807089]]


In [11]:
# i.a. How can you show that columns of Q is in the column space of A?
print('''Columns of Q are in column space of A if rank [A q_j] == rank A,
where q_j are the columns of Q and j = 1,2...,n.\n''')

print("rank A =", rank_A)
rank_equivalent = 1
for j in range(n):
    A_q_j = np.hstack((A, np.vstack(Q[:,j])))
    rank_A_q_j = la.matrix_rank(A_q_j)
    print(f"rank [A q_{j+1}] =", rank_A_q_j)
    if rank_A_q_j != rank_A:
        rank_equivalent = 0
if rank_equivalent:
    print("\nColumns of Q are in column space of A.")
else:
    print("\nColumns of Q are not in column space of A.")

Columns of Q are in column space of A if rank [A q_j] == rank A,
where q_j are the columns of Q and j = 1,2...,n.

rank A = 2
rank [A q_1] = 2
rank [A q_2] = 2

Columns of Q are in column space of A.


In [12]:
# i.b. Solve Qx = b, what is the error of approximating b?
# Is it the same as e.? Why?
Q_inv = la.pinv(Q)
x1q = Q_inv@b
print("x =\n",x1q)

error_1q = b - Q@x1q
norm_error_1q = la.norm(error_1q)
print("\nError of approximating b =", norm_error_1q)

if la.norm(error_1q - error_1b) <= 1e-6:
    print("It is the same as Question e).")
else:
    print("It is not the same as Question e).")

x =
 [[-1.17102581]
 [-0.13492227]]

Error of approximating b = 0.04735215828881781
It is the same as Question e).


In [13]:
# j. Evaluate N point(e.g,10) around the least squares solution(normal equation)
# when it exist to show that it gives the least error squares in approximating b.
# Specifically, new_x = x + delta_x.
# Additionally make delta_x has norm(1) generated by numpy.random.rand

N = randint(1,100)
errExample = np.zeros(N)
for i in range(N):
    delta_x = np.random.rand(n,1)
    delta_x = delta_x/la.norm(delta_x)
    new_x = x1b + delta_x
    new_hat_b = A@new_x
    errExample[i] = la.norm(b-new_hat_b)
print(f'''norm approximation by LS = {norm_error_1b},
by {N} examples (minErr={min(errExample)}, meanErr={mean(errExample)})''')


norm approximation by LS = 0.04735215828881794,
by 73 examples (minErr=0.8863293517571902, meanErr=1.247862160709278)


### Question 4B

In [14]:
# a. Given (AX-A)^-1 = X^-1BC^-1, manually solve for X. Clearly write the derivation and assumption.
print("Assuming all the matrices A, B, C and X are square and invertible,")
print("(AX - A)^-1 = (X^_-1)BC^-1")
print("X(AX - A)^-1 = BC^-1")
print("(AX - A)X^-1 = CB^-1")
print("A - AX^-1 = CB^-1")
print("A - CB^-1 = AX^-1")
print("XA^-1 = (A - CB^-1)^-1")
print("X = ((A - CB^-1)^-1)A")
print("X = ((A^-1)(A - CB^-1))^-1")
print("\nTherefore,\nX = (I - (A^-1)CB^-1)^-1")

Assuming all the matrices A, B, C and X are square and invertible,
(AX - A)^-1 = (X^_-1)BC^-1
X(AX - A)^-1 = BC^-1
(AX - A)X^-1 = CB^-1
A - AX^-1 = CB^-1
A - CB^-1 = AX^-1
XA^-1 = (A - CB^-1)^-1
X = ((A - CB^-1)^-1)A
X = ((A^-1)(A - CB^-1))^-1

Therefore,
X = (I - (A^-1)CB^-1)^-1


In [15]:
# b. Calculate X using found equation.
A = np.random.rand(3,3)
B = np.random.rand(3,3)
C = np.random.rand(3,3)
print("A =\n",A)
print("B =\n",B)
print("C =\n",C)

X = la.inv(np.eye(3)-la.inv(A)@C@la.inv(B))
print("X =\n",X)

LHS = la.inv(A@X - A)
RHS = la.inv(X)@B@la.inv(C)

print("LHS:\n(AX-A)^-1 =\n",LHS)
print("RHS:\n(X^-1)BC^-1 =\n",RHS)
if la.norm(LHS-RHS) <= 1e-6:
    print("\nSince LHS == RHS, therefore X found is correct.")

A =
 [[0.60831786 0.98395404 0.09303464]
 [0.48318936 0.66908514 0.71579483]
 [0.25062419 0.41015841 0.53347835]]
B =
 [[0.51365727 0.61869072 0.20788217]
 [0.08932533 0.61944456 0.86722755]
 [0.06800123 0.94295899 0.76622335]]
C =
 [[0.02768658 0.79142562 0.30123458]
 [0.7586896  0.837045   0.89696593]
 [0.25109645 0.59974715 0.61879309]]
X =
 [[0.24437804 0.70549199 1.76783649]
 [0.84308965 1.30351717 0.60495712]
 [0.8538305  1.4308905  1.56673212]]
LHS:
(AX-A)^-1 =
 [[  2.69244684 -12.31071576  15.95592288]
 [ -2.68615598   7.64386318  -8.14765621]
 [  1.22014623  -0.60878418  -0.08995902]]
RHS:
(X^-1)BC^-1 =
 [[  2.69244684 -12.31071576  15.95592288]
 [ -2.68615598   7.64386318  -8.14765621]
 [  1.22014623  -0.60878418  -0.08995902]]

Since LHS == RHS, therefore X found is correct.
