# Lab 3
## 4. Tasks
### Question 1

In [1]:
import numpy as np
from numpy import linalg as la
import pandas as pd
import dill

In [2]:
# Q1. Dot Product, Norm, Cosine Similarity

# a. Initialising 5x4 data matrix raw_A1 from Table 1
raw_A1 = [[62.2, 171.1, 17, 36.8],
          [52.2, 162.6, 19, 36.5],
          [72.3, 178.2, 22, 36.7],
          [80.8, 185.2, 24, 37.9],
          [72.5, 178.3, 22, 37.8]]
raw_A1 = np.array(raw_A1, dtype = float)
A1 = []
for row in raw_A1:
    A1.append(row[:-1])
print("A1  = ", end = "")
print('\t' + str(np.vstack(A1)).replace('\n','\n\t'))

A1  = 	[[ 62.2 171.1  17. ]
	 [ 52.2 162.6  19. ]
	 [ 72.3 178.2  22. ]
	 [ 80.8 185.2  24. ]
	 [ 72.5 178.3  22. ]]


In [3]:
# b. How will you measure the similarity between two
#    persons based on the norm and dot product?

print('''Using the formula of cos(theta) = u.v / (||u|| * ||v||),
where u & v are vectors representing the two persons.
The closer the cosine value of the two persons is to 1,
the more similar these two persons are.''')

Using the formula of cos(theta) = u.v / (||u|| * ||v||),
where u & v are vectors representing the two persons.
The closer the cosine value of the two persons is to 1,
the more similar these two persons are.


In [4]:
# c. Implementing my own functions
def my_norm(x):
    mySum = 0
    for i in np.nditer(x):
        mySum += i*i
    return np.sqrt(mySum)

def my_dot(x, y):
    mySum = 0
    for i, j in np.nditer((x, y)):
        mySum += i * j
    return mySum

def my_cosSimilarity(x, y):
    # x.y = ||x|| * ||y|| * cos(theta)
    # cos(theta) = x.y / (||x|| * ||y||)
    dividend = my_dot(x, y)
    divisor = my_norm(x) * my_norm(y)
    return dividend / divisor

In [5]:
# d. Comparing my functions to built-in numpy functions.
Bob, Alice = A1[0], A1[1]
print("Norm Comparison")
print("Bob's Norm")
print("my_norm =", my_norm(Bob), "vs numPy =", np.linalg.norm(Bob))
print()
print("Alice's Norm")
print("my_norm =", my_norm(Alice), "vs numPy =", np.linalg.norm(Alice))
print()
print("Dot Product Comparison")
print("my_dot =", my_dot(Bob, Alice), "vs numPy =", np.dot(Bob, Alice))
print()
print("Consine Similarity Comparison")
print("my_cosSimilarity =", my_cosSimilarity(Bob, Alice), \
      "vs numPy =", np.dot(Bob, Alice)/(np.linalg.norm(Bob)*np.linalg.norm(Alice)))

Norm Comparison
Bob's Norm
my_norm = 182.84706724473324 vs numPy = 182.84706724473324

Alice's Norm
my_norm = 171.8272388185296 vs numPy = 171.8272388185296

Dot Product Comparison
my_dot = 31390.699999999997 vs numPy = 31390.699999999997

Consine Similarity Comparison
my_cosSimilarity = 0.9991276784753994 vs numPy = 0.9991276784753994


In [6]:
# e. Obtaining A1_norm by normalizing each row of A1 to unit vector
# Unit vector = vector / norm of vector
def my_normalizing(matrix):
    matrix_norm = []
    for row in matrix:
        matrix_norm.append(row/my_norm(row))
    return matrix_norm
A1_norm = np.vstack(my_normalizing(A1))
print("A1_norm    =", end = "")
print('\t' + str(A1_norm).replace('\n','\n\t\t'))

A1_norm    =	[[0.34017499 0.93575469 0.09297387]
		 [0.30379351 0.94629932 0.11057618]
		 [0.37352232 0.92063178 0.11365824]
		 [0.39709269 0.91016789 0.11794832]
		 [0.37423304 0.92035519 0.11356037]]


In [7]:
# f. Repeat Q1d using normalized vector Matrix A1_norm
Bob_norm, Alice_norm = A1_norm[0], A1_norm[1]
print("Norm Comparison")
print("Bob's Norm")
print("my_norm =", my_norm(Bob_norm), "vs numPy =", np.linalg.norm(Bob_norm))
print()
print("Alice's Norm")
print("my_norm =", my_norm(Alice_norm), "vs numPy =", np.linalg.norm(Alice_norm))
print()
print("Dot Product Comparison")
print("my_dot =", my_dot(Bob_norm, Alice_norm), "vs numPy =", np.dot(Bob_norm, Alice_norm))
print()
print("Consine Similarity Comparison")
print("my_cosSimilarity =", my_cosSimilarity(Bob_norm, Alice_norm), \
      "vs numPy =", np.dot(Bob_norm, Alice_norm)/(np.linalg.norm(Bob_norm)*np.linalg.norm(Alice_norm)))

Norm Comparison
Bob's Norm
my_norm = 1.0 vs numPy = 1.0

Alice's Norm
my_norm = 0.9999999999999999 vs numPy = 0.9999999999999999

Dot Product Comparison
my_dot = 0.9991276784753995 vs numPy = 0.9991276784753995

Consine Similarity Comparison
my_cosSimilarity = 0.9991276784753996 vs numPy = 0.9991276784753996


In [8]:
# g. Comparing consine similarity of unknown person against the rest
unknown = A1_norm[-1]
b = [] # Similarity measure vector b
for i in range(4):
    b.append(my_cosSimilarity(unknown, A1_norm[i]))
b = np.vstack(b)
print("Similarity vector b:")
print("b   = ", end = "")
print('\t' + str(b).replace('\n','\n\t'))

Similarity vector b:
b   = 	[[0.99908955]
	 [0.99717813]
	 [0.9999997 ]
	 [0.9996772 ]]


In [9]:
# h. Which person on the table is most similar to the unknown person?
print(
'''Charlie is the most similar to the unknown person because his
similarity measure is the highest compared to the rest.'''
)

Charlie is the most similar to the unknown person because his
similarity measure is the highest compared to the rest.


### Question 2

In [10]:
# Q2. Projection, Orthogonality

# a. Which matrix's (A or B) columns form an orthogonal set? Why?
A = [[1, 1, 1],
     [1, 1, 1],
     [1, 1, -1],
     [1, -1, -1]]
B = [[3, -1, -1/2],
     [1, 2, -2],
     [1, 1, 7/2],
     [0, 1, 0]]

# my_transpose function to transpose matrix
def my_transpose(A):
    transposed = np.zeros(shape=(len(A[0]),len(A)))
    for i in range(len(A)):
        for j in range(len(A[0])):
            transposed[j][i] = A[i][j]
    return transposed

# Column vectors of matrix are orthogonal if their dot product = 0
# Function comparing each column to check if they are orthogonal
def is_orthogonal(matrix):
    m_T = my_transpose(matrix)
    for i in range(-1, -(len(m_T)+1), -1):
        dot_product = my_dot(m_T[i], m_T[i+1])
        if dot_product != 0:
            return False
            break
    return True
print("Do matrix A's columns form an orthogonal set?",is_orthogonal(A))
print("Do matrix B's columns form an orthogonal set?",is_orthogonal(B))
print(
'''\nColumns of B form an orthogonal set because the dot products
between the columns = 0'''
)

B_T = my_transpose(B)
col1_col2 = my_dot(B_T[0], B_T[1])
col1_col3 = my_dot(B_T[0], B_T[2])
col2_col3 = my_dot(B_T[1], B_T[2])

print("The dot product of b1 and b2 is", col1_col2)
print("The dot product of b1 and b3 is", col1_col3)
print("The dot product of b2 and b3 is", col2_col3)

Do matrix A's columns form an orthogonal set? False
Do matrix B's columns form an orthogonal set? True

Columns of B form an orthogonal set because the dot products
between the columns = 0
The dot product of b1 and b2 is 0.0
The dot product of b1 and b3 is 0.0
The dot product of b2 and b3 is 0.0


In [11]:
# b. Show that solution Bx is equals to y1
y1 = [[2.5], 
      [11], 
      [-7.5], 
      [2]]
x = np.zeros(shape=(3,1))
for i in range(3):
    b_i = np.vstack(B_T[i]) # column of B
    x[i] = my_dot(y1, b_i)/my_dot(b_i, b_i)
    
# Vector x such that y1 = Bx
print("x   = ", end = "")
print('\t' + str(x).replace('\n','\n\t'))

# Prove that Bx = y1
print("\nProve that Bx = y1")
print("Bx  = ", end = "")
print('\t' + str(B@x).replace('\n','\n\t'))

x   = 	[[ 1.]
	 [ 2.]
	 [-3.]]

Prove that Bx = y1
Bx  = 	[[ 2.5]
	 [11. ]
	 [-7.5]
	 [ 2. ]]


In [12]:
# c. Using Theorem 5 to solve for Ax = y2

y2 = [[1], 
      [2], 
      [-3], 
      [0]]
x2 = np.zeros(shape=(3,1))
for i in range(3):
    A_T = my_transpose(A)
    a_i = np.vstack(A_T[i]) # column of B
    x2[i] = my_dot(y2, a_i)/my_dot(a_i, a_i)
    
# Found x using Theorem 5
print("x   = ", end = "")
print('\t' + str(x2).replace('\n','\n\t'))

# Ax
print("Ax  = ", end = "")
print('\t' + str(A@x2).replace('\n','\n\t'))
print(
'''It is wrong to use Theorem 5 to solve for x in this case 
because A is not an orthogonal matrix.''')

x   = 	[[0. ]
	 [0. ]
	 [1.5]]
Ax  = 	[[ 1.5]
	 [ 1.5]
	 [-1.5]
	 [-1.5]]
It is wrong to use Theorem 5 to solve for x in this case 
because A is not an orthogonal matrix.


In [13]:
# d. Show that the columns of Bn forms an orthonormal set 

B_n = my_transpose(my_normalizing(np.vstack(B_T)))
print(B_n)

'''sum1, sum2, sum3 = 0,0,0
for i in range(4):
    for j in range(3):
        b = B_n[i][j]
        if j == 0:
            sum1 += b*b
        elif j == 1:
            sum2 += b*b
        elif j == 2:
            sum3 += b*b
print(sum1**0.5)
print(sum2**0.5)
print(sum3**0.5)'''

orthonomality_check = np.dot(np.transpose(B_n), B_n)
print(orthonomality_check)
# Verify if the 3-by-3 BTB approximates a 3-by-3 identity matrix
print('\nOrthonormality holds?', np.allclose(orthonomality_check, np.eye(3)),'\n')

# Solve for y1 = B_nx_n
x_n = np.zeros(shape=(3,1))
B_n_T = my_transpose(B_n)
for i in range(3):
    b_n_i = np.vstack(B_n_T[i]) # column of B_n
    x_n[i] = my_dot(y1, b_n_i)/my_dot(b_n_i, b_n_i)
    
# Vector x_n such that y1 = B_nx_n
print("x_n = ", end = "")
print('\t' + str(x).replace('\n','\n\t'))

# Prove that B_nx_n = y1
print("Prove that B_nx_n = y1")
print("B_nx_n=", end = "")
print('\t' + str(B@x).replace('\n','\n\t'))
print("\nx_n is the same vector as x found in Q2b.")

[[ 0.90453403 -0.37796447 -0.12309149]
 [ 0.30151134  0.75592895 -0.49236596]
 [ 0.30151134  0.37796447  0.86164044]
 [ 0.          0.37796447  0.        ]]
[[1.00000000e+00 9.56207044e-18 3.00799601e-17]
 [9.56207044e-18 1.00000000e+00 1.91220253e-17]
 [3.00799601e-17 1.91220253e-17 1.00000000e+00]]

Orthonormality holds? True 

x_n = 	[[ 1.]
	 [ 2.]
	 [-3.]]
Prove that B_nx_n = y1
B_nx_n=	[[ 2.5]
	 [11. ]
	 [-7.5]
	 [ 2. ]]

x_n is the same vector as x found in Q2b.


In [14]:
# e. Find the projection of y1 on the columns of B
# Calculate the error of approximation for each column
# error = ||y1 - y_hat||
errors = []
for i in range(3):
    b_i = np.vstack(B_T[i]) # column of B
    proj = ((my_dot(y1, b_i))/(my_dot(b_i, b_i)))*(b_i)
    print("The projection of y1 on b" + str(i+1), "=\n", proj)
    error = my_norm(y1 - proj) # y_hat == proj
    errors.append(error)
    print("The error of approximation is", error, "\n")
    
print('''Since, the projections of y1 on the columns of B carries
relatively large error of approximation, it is important to 
use B_n columns to approximate y1.''')

The projection of y1 on b1 =
 [[3.]
 [1.]
 [1.]
 [0.]]
The error of approximation is 13.285330255586423 

The projection of y1 on b2 =
 [[-2.]
 [ 4.]
 [ 2.]
 [ 2.]]
The error of approximation is 12.62933094031509 

The projection of y1 on b3 =
 [[  1.5]
 [  6. ]
 [-10.5]
 [ -0. ]]
The error of approximation is 6.244997998398398 

Since, the projections of y1 on the columns of B carries
relatively large error of approximation, it is important to 
use B_n columns to approximate y1.


In [15]:
# f. Choose 2 columns of B to approximate y1
print('''I will use columns b2 & b3 since they carry the least
error of approximation of {0} &
{1} respectively.'''.format(errors[1], errors[2]))

I will use columns b2 & b3 since they carry the least
error of approximation of 12.62933094031509 &
6.244997998398398 respectively.


### Question 3

In [16]:
# Q3. Gram-Schmidt Process
# a. Applying GSP on A so that A = QR

def gram_schmidt(A):
# The classical Gram Schmidt process.
# Input: an arbitrary mxp matrix.
# Output: the Q factors of the input.   

    n = A.shape[1]
    Q = np.zeros(A.shape)
    
    for i in range(n):
        xi = A[:, i]
        vi = xi
        for j in range(i):
            # Since Q[:,j] is always a unit vector,
            # no need to implement the denominator. 
            vi = vi - np.dot(xi, Q[:,j])*Q[:,j] 

        Q[:, i] = vi/la.norm(vi)
    
    return Q

def qr_mod_gram_schmidt(A):
# The QR factorization using the modified Gram Schmidt process.
# Input: an arbitrary mxp matrix.
# Output: the Q and R factors of the input.

    # Obtain the column number.
    p = A.shape[1]
    
    # Initiate the Q and R factors.
    Q = A.copy() # Prevent A from being changed.
    R = np.zeros((p,p))
    
    # Iterate for each column of the input.
    for k in range(p):
        w = A[:, k]
        
        ##### Different part. #####
        for i in range(k):
            R[i, k] = Q[:, i].dot(w)
            w = w - R[i, k] * Q[:, i]
        ###########################
        
        R[k, k] = la.norm(w)
        Q[:, k] = w / R[k, k]
            
    return Q, R

A = np.array(A, dtype = float)
QR = qr_mod_gram_schmidt(A)
Q, R = QR[0], QR[1]
print("Q   = ", end = "")
print('\t' + str(Q).replace('\n','\n\t'))
print()
print("R   = ", end = "")
print('\t' + str(R).replace('\n','\n\t'))
print("\nThe number of columns of Q = 3.")
print("The number of columns of A = 3.")
print("Therefore, the number of columns of Q == A.")

Q   = 	[[ 5.00000000e-01  2.88675135e-01  4.08248290e-01]
	 [ 5.00000000e-01  2.88675135e-01  4.08248290e-01]
	 [ 5.00000000e-01  2.88675135e-01 -8.16496581e-01]
	 [ 5.00000000e-01 -8.66025404e-01  1.35973996e-16]]

R   = 	[[2.         1.         0.        ]
	 [0.         1.73205081 1.15470054]
	 [0.         0.         1.63299316]]

The number of columns of Q = 3.
The number of columns of A = 3.
Therefore, the number of columns of Q == A.


In [17]:
# b. What are the characteristics of columns of Q? 
# Explain your answer and compare Q'*Q vs Q*Q'. 
# What is the matrix Q*Q' and its relationship to A?

print("The columns of Q are orthogonal such that Q'*Q = I")
QT_Q = my_transpose(Q)@Q
print("Q'*Q = ", end = "")
print('\t' + str(QT_Q).replace('\n','\n\t'))
print()


Q_QT = Q@my_transpose(Q)
print("Q*Q' =")
print(Q_QT)
print()
print("But since Q*Q' != I, Q is not an orthogonal matrix.")
print("Q*Q' is the projection matrix with the column space of A.")


The columns of Q are orthogonal such that Q'*Q = I
Q'*Q = 	[[ 1.00000000e+00  5.55111512e-17 -9.85464559e-17]
	 [ 5.55111512e-17  1.00000000e+00 -2.12120825e-16]
	 [-9.85464559e-17 -2.12120825e-16  1.00000000e+00]]

Q*Q' =
[[ 5.00000000e-01  5.00000000e-01  8.09214782e-17  4.35649885e-18]
 [ 5.00000000e-01  5.00000000e-01  8.09214782e-17  4.35649885e-18]
 [ 8.09214782e-17  8.09214782e-17  1.00000000e+00 -1.62176955e-16]
 [ 4.35649885e-18  4.35649885e-18 -1.62176955e-16  1.00000000e+00]]

But since Q*Q' != I, Q is not an orthogonal matrix.
Q*Q' is the projection matrix with the column space of A.


In [18]:
# c. Finding ranks of A with row reduction
def rref(A):
    M = A.copy()
    tol = 1e-14
    #A = B.copy()
    rows, cols = M.shape
    r = 0
    pivots_pos = []
    row_exchanges = np.arange(rows)
    for c in range(cols):
        ## Find the pivot row:
        pivot = np.argmax (np.abs (M[r:rows,c])) + r
        m = np.abs(M[pivot, c])
        
        if m <= tol:
        ## Skip column c, making sure the approximately zero terms are
        ## actually zero.
            M[r:rows, c] = np.zeros(rows-r)
        else:
            ## keep track of bound variables
            pivots_pos.append((r,c))

            if pivot != r:
                ## Swap current row and pivot row
                M[[pivot, r], c:cols] = M[[r, pivot], c:cols]
                row_exchanges[[pivot,r]] = row_exchanges[[r,pivot]]

            ## Normalize pivot row
            M[r, c:cols] = M[r, c:cols] / M[r, c];

            ## Eliminate the current column
            v = M[r, c:cols]
            ## Above (before row r):
            if r > 0:
                ridx_above = np.arange(r)
                M[ridx_above, c:cols] = M[ridx_above, c:cols] - np.outer(v, M[ridx_above, c]).T
                ## Below (after row r):
            if r < rows-1:
                ridx_below = np.arange(r+1,rows)
                M[ridx_below, c:cols] = M[ridx_below, c:cols] - np.outer(v, M[ridx_below, c]).T
                r += 1
        ## Check if done
        if r == rows:
            break;
    return M
rref_A = rref(A)
print("rref_A=", end = "")
print('\t' + str(rref_A).replace('\n','\n\t'))
print('''\nSince there are 3 pivots in the reduced row echelon form of A,
the rank of A = 3.\n''')
print('''We can confirm using a numpy function:
numpy.linalg.matrix_rank(A) = {0}'''.format(la.matrix_rank(A)))

rref_A=	[[1. 0. 0.]
	 [0. 1. 0.]
	 [0. 0. 1.]
	 [0. 0. 0.]]

Since there are 3 pivots in the reduced row echelon form of A,
the rank of A = 3.

We can confirm using a numpy function:
numpy.linalg.matrix_rank(A) = 3


In [19]:
# d. Finding rank of augmented matrix [A Q]
AQ = np.column_stack((A,Q))
print("Rank of augmented matrix [A Q] =", la.matrix_rank(AQ))
print('''The rank of augmented matrix [A Q] == rank of A.
This shows that Q and A has the same column space.''')

Rank of augmented matrix [A Q] = 3
The rank of augmented matrix [A Q] == rank of A.
This shows that Q and A has the same column space.


In [20]:
# e. Finding projection p using 2 methods
# Method 1: Take U = {u1, u2, ... , un} as a set of basis, 
# find the projection of y onto each ui, and sum them up.

def my_orthogonal_proj_1(Q, y):
    w = np.zeros(np.shape(Q))
    proj_p1 = np.zeros(np.shape(Q)[0])
    for i in range(np.shape(Q)[1]):
        w[:,i] = my_dot(y,Q[:,i])*Q[:,i]
        proj_p1 += w[:,i]
    return proj_p1

# Method 2: Apply projection matrix P to y.
def my_orthogonal_proj_2(Q, y):
    Q_QT = Q@my_transpose(Q)
    proj_p2 = Q_QT@y
    return proj_p2


In [22]:
# f. Finding closest point in Col A space to y = (1,2,3,4)
y = (1,2,3,4)
p1 = my_orthogonal_proj_1(Q, y)
p2 = my_orthogonal_proj_2(Q, y)
error1 = my_norm(y - p1)
error2 = my_norm(y - p2)
print("Using first method:\nprojection p1 =", p1)
print("error1 =", error1)
print("\nUsing second method:\nprojection p2 =", p2)
print("error2 =", error2)

Using first method:
projection p1 = [1.5 1.5 3.  4. ]
error1 = 0.7071067811865476

Using second method:
projection p2 = [1.5 1.5 3.  4. ]
error2 = 0.7071067811865476
